"""MetaReport models — Level 10 pipeline health monitoring.

Contains AgentHealthScore, DebateBalance, ActionEffectiveness, and MetaReport.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class AgentHealthScore(BaseModel):
    """Health metrics for a single agent."""
    agent_name: str
    run_count: int = 0
    avg_quality_score: float = 0.0
    error_rate: float = 0.0
    avg_latency_ms: float = 0.0
    trend: str = "STABLE"  # IMPROVING / STABLE / DEGRADING
    issues: list[str] = Field(default_factory=list)


class DebateBalance(BaseModel):
    """Red vs Blue team win rate analysis."""
    red_team_win_rate: float = 0.5
    blue_team_win_rate: float = 0.5
    balance_status: str = "BALANCED"  # BALANCED / RED_DOMINANT / BLUE_DOMINANT
    recommendation: str = ""


class ActionEffectiveness(BaseModel):
    """Action execution and effectiveness metrics."""
    total_actions: int = 0
    acted_on_rate: float = 0.0
    auto_execute_rate: float = 0.0
    approval_rate: float = 0.0
    rejection_rate: float = 0.0
    effectiveness_score: float = 0.0  # composite 0.0-1.0


class MetaReport(BaseModel):
    """System-wide health report generated by MetaAgent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    period_start: datetime = Field(default_factory=datetime.utcnow)
    period_end: datetime = Field(default_factory=datetime.utcnow)
    runs_analysed: int = 0
    agent_health: list[AgentHealthScore] = Field(default_factory=list)
    debate_balance: DebateBalance = Field(default_factory=DebateBalance)
    action_effectiveness: ActionEffectiveness = Field(default_factory=ActionEffectiveness)
    forecast_accuracy: float = 0.0
    overall_health: float = 1.0  # 0.0-1.0 composite
    critical_issues: list[str] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    def to_payload(self) -> dict:
        """Serialize to JSON-compatible dict."""
        return {
            "id": self.id,
            "period_start": self.period_start.isoformat(),
            "period_end": self.period_end.isoformat(),
            "runs_analysed": self.runs_analysed,
            "agent_health": [ah.model_dump() for ah in self.agent_health],
            "debate_balance": self.debate_balance.model_dump(),
            "action_effectiveness": self.action_effectiveness.model_dump(),
            "forecast_accuracy": self.forecast_accuracy,
            "overall_health": self.overall_health,
            "critical_issues": self.critical_issues,
            "recommendations": self.recommendations,
            "created_at": self.created_at.isoformat(),
            "type": "meta_report",
        }

    @classmethod
    def from_payload(cls, data: dict) -> MetaReport:
        """Deserialize from dict."""
        data = dict(data)
        data.pop("type", None)
        if isinstance(data.get("period_start"), str):
            data["period_start"] = datetime.fromisoformat(data["period_start"])
        if isinstance(data.get("period_end"), str):
            data["period_end"] = datetime.fromisoformat(data["period_end"])
        if isinstance(data.get("created_at"), str):
            data["created_at"] = datetime.fromisoformat(data["created_at"])
        if "agent_health" in data and data["agent_health"]:
            data["agent_health"] = [
                AgentHealthScore(**ah) if isinstance(ah, dict) else ah
                for ah in data["agent_health"]
            ]
        if "debate_balance" in data and isinstance(data["debate_balance"], dict):
            data["debate_balance"] = DebateBalance(**data["debate_balance"])
        if "action_effectiveness" in data and isinstance(data["action_effectiveness"], dict):
            data["action_effectiveness"] = ActionEffectiveness(**data["action_effectiveness"])
        return cls(**data)
